import shoeImage from "../assets/shoe.png";

const products = [
  {
    id: 1,
    title: "Bandana Travis X Nike",
    images: [
      shoeImage,
      "/productPics/shoe1/Bandana.jpg",
      "/productPics/shoe1/Bandana1.jpg",
      "/productPics/shoe1/Bandana2.jpg",
    ],
    description: "Comfy stylish shoe",
    sizes: [38, 39, 40, 41, 42, 43],
    price: 120,
    category: "unisex",
  },
  {
    id: 2,
    title: "Travis AllBlack",
    images: [
      "/productPics/shoe1/AllBlack1.jpg",
      "/productPics/shoe1/AllBlack2.jpg",
    ],
    description: "For Dark nights",
    sizes: [40, 41, 42, 43],
    price: 99.99,
    category: "men",
  },
  {
    id: 3,
    title: "Nike Green Dragon",
    images: ["/productPics/shoe2/greenDragon.jpg"],
    description: "Low Tier",
    sizes: [38, 39, 40, 41],
    price: 150,
    category: "women",
  },
  {
    id: 4,
    title: "Red & White Converse",
    images: [
      "/productPics/shoe3/whiteRedConverse.jpg",
      "/productPics/shoe3/whiteRedConverse2.jpg",
    ],
    description: "High Tier",
    sizes: [37, 38, 39, 40, 41],
    price: 80,
    category: "women",
  },
  {
    id: 5,
    title: "Nike SB Dragon",
    images: ["/productPics/shoe4/nikeSbDragon.jpg"],
    description: "Beauty in minimalism",
    sizes: [39, 40, 41, 42],
    price: 299,
    category: "women",
  },
  {
    id: 6,
    title: "Nike X Oreo",
    images: ["/productPics/shoe5/nikeOreo.jpg"],
    description: "A Delicious Collab!",
    sizes: [37, 38, 39, 40, 41],
    price: 150,
    category: "unisex",
  },
  {
    id: 7,
    title: "Nike X Kaws",
    images: ["/productPics/shoe6/nikeKaws.jpg"],
    description: "Steal all the looks!",
    sizes: [37, 38, 39, 40, 41],
    price: 499,
    category: "men",
  },
  {
    id: 8,
    title: "J5 Zen",
    images: ["/productPics/shoe7/nikeZen.jpg"],
    description: "The beauty of shines!",
    sizes: [37, 38, 39, 40, 41],
    price: 249,
    category: "women",
  },
  {
    id: 9,
    title: "Puma Street",
    images: ["/productPics/shoe8/nikeB&B.jpg"],
    description: "Feeling feather under your feet",
    sizes: [37, 38, 39, 40, 41],
    price: 119,
    category: "unisex",
  },
  {
    id: 10,
    title: "All Star 1970",
    images: ["/productPics/shoe9/allStar1970.jpg"],
    description: "Comfy & plain",
    sizes: [37, 38, 39, 40, 41],
    price: 69,
    category: "unisex",
  },
  {
    id: 11,
    title: "Travis X Nike Velvet",
    images: ["/productPics/shoe10/travisVelvet.jpg"],
    description: "another great dark themes collab!",
    sizes: [37, 38, 39, 40, 41],
    price: 249,
    category: "men",
  },
  {
    id: 12,
    title: "Travis Baby Blue & White",
    images: ["/productPics/shoe11/travisBabyBlue.jpg"],
    description: "Baby CUTIE Blue!",
    sizes: [37, 38, 39, 40, 41],
    price: 339,
    category: "men",
  },
  {
    id: 13,
    title: "Travis X Nike Pink Pony",
    images: ["/productPics/shoe12/nikePony.jpg"],
    description: "Pink Pony for all weathers.",
    sizes: [37, 38, 39, 40, 41],
    price: 449,
    category: "women",
  },
  {
    id: 14,
    title: "Travis Utopia Special",
    images: ["/productPics/shoe13/TravisUtopia.jpg"],
    description: "Just like the album, MASTERPIECE!",
    sizes: [37, 38, 39, 40, 41],
    price: 499,
    category: "men",
  },
  {
    id: 15,
    title: "Travis X Nike white & gray",
    images: ["/productPics/shoe14/travisGrey.jpg"],
    description: "Comfy and Stylish.",
    sizes: [37, 38, 39, 40, 41],
    price: 149,
    category: "unisex",
  },
  {
    id: 16,
    title: "travis x nike olive",
    images: ["/productPics/shoe15/travisOlive.jpg"],
    description: "a risky option",
    sizes: [37, 38, 39, 40, 41],
    price: 229,
    category: "unisex",
  },

  {
    id: 17,
    title: "Bandana Travis X Nike",
    images: [shoeImage],
    description: "Comfy stylish shoe",
    sizes: [37, 38, 39, 40, 41],
    price: 120,
    category: "unisex",
  },
  {
    id: 18,
    title: "Travis AllBlack",
    images: ["/productPics/shoe1/AllBlack1.jpg"],
    description: "For Dark nights",
    sizes: [37, 38, 39, 40, 41],
    price: 99.99,
    category: "men",
  },
  {
    id: 19,
    title: "Nike Green Dragon",
    images: ["/productPics/shoe2/greenDragon.jpg"],
    description: "Low Tier",
    sizes: [37, 38, 39, 40, 41],
    price: 150,
    category: "women",
  },
  {
    id: 29,
    title: "Red & White Converse",
    images: ["/productPics/shoe3/whiteRedConverse.jpg"],
    description: "High Tier",
    sizes: [37, 38, 39, 40, 41],
    price: 80,
    category: "women",
  },
  {
    id: 21,
    title: "Nike SB Dragon",
    images: ["/productPics/shoe4/nikeSbDragon.jpg"],
    description: "Beauty in minimalism",
    sizes: [37, 38, 39, 40, 41],
    price: 299,
    category: "women",
  },
  {
    id: 22,
    title: "Nike X Oreo",
    images: ["/productPics/shoe5/nikeOreo.jpg"],
    description: "A Delicious Collab!",
    sizes: [37, 38, 39, 40, 41],
    price: 150,
    category: "unisex",
  },
  {
    id: 23,
    title: "Nike X Kaws",
    images: ["/productPics/shoe6/nikeKaws.jpg"],
    description: "Steal all the looks!",
    sizes: [37, 38, 39, 40, 41],
    price: 499,
    category: "men",
  },
  {
    id: 24,
    title: "J5 Zen",
    images: ["/productPics/shoe7/nikeZen.jpg"],
    description: "The beauty of shines!",
    sizes: [37, 38, 39, 40, 41],
    price: 249,
    category: "women",
  },
  {
    id: 25,
    title: "Puma Street",
    images: ["/productPics/shoe8/nikeB&B.jpg"],
    description: "Feeling feather under your feet",
    sizes: [37, 38, 39, 40, 41],
    price: 119,
    category: "unisex",
  },
  {
    id: 26,
    title: "All Star 1970",
    images: ["/productPics/shoe9/allStar1970.jpg"],
    description: "Comfy & plain",
    sizes: [37, 38, 39, 40, 41],
    price: 69,
    category: "unisex",
  },
  {
    id: 27,
    title: "Travis X Nike Velvet",
    images: ["/productPics/shoe10/travisVelvet.jpg"],
    description: "another great dark themes collab!",
    sizes: [37, 38, 39, 40, 41],
    price: 249,
    category: "men",
  },
  {
    id: 28,
    title: "Travis Baby Blue & White",
    images: ["/productPics/shoe11/travisBabyBlue.jpg"],
    description: "Baby CUTIE Blue!",
    sizes: [37, 38, 39, 40, 41],
    price: 339,
    category: "men",
  },
  {
    id: 29,
    title: "Travis X Nike Pink Pony",
    images: ["/productPics/shoe12/nikePony.jpg"],
    description: "Pink Pony for all weathers.",
    sizes: [37, 38, 39, 40, 41],
    price: 449,
    category: "women",
  },
  {
    id: 30,
    title: "Travis Utopia Special",
    images: ["/productPics/shoe13/TravisUtopia.jpg"],
    description: "Just like the album, MASTERPIECE!",
    sizes: [37, 38, 39, 40, 41],
    price: 499,
    category: "men",
  },
  {
    id: 31,
    title: "Travis X Nike white & gray",
    images: ["/productPics/shoe14/travisGrey.jpg"],
    description: "Comfy and Stylish.",
    sizes: [37, 38, 39, 40, 41],
    price: 149,
    category: "unisex",
  },
  {
    id: 32,
    title: "travis x nike olive",
    images: ["/productPics/shoe15/travisOlive.jpg"],
    description: "a risky option",
    sizes: [37, 38, 39, 40, 41],
    price: 229,
    category: "unisex",
  },
];

export default products;
